#! bin/bash
echo "Good Evening"
echo "Please Enter your salary"
read sal
if [ $sal -le 10000 ]
then
echo "in this $sal sal there is no tax"
elif [ $sal -gt 10000 ] && [ $sal -le 25000 ]
then
echo "in this $sal sal 5% tax is included"
elif [ $sal -gt 25000 ]
then 
echo "in this $sal sal 10% tax is deducted"
fi
