#! bin/bash
echo "Good Evening"
echo "Please Enter your salary"
read sal
if [ $sal -le 10000 ]
then
echo "in this $sal sal there is no tax"
elif [ $sal -gt 10000 ] && [ $sal -le 25000 ]
then
res=$(( sal * 5/100 ))
sal=$(( sal - res ))
echo "total $sal after adding 5% tax "
elif [ $sal -gt 25000 ]
then
res=$(( sal * 10/100 ))
sal=$(( sal -res ))
echo "total sal $sal after 10% tax is deducted"
fi
